name: Production Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  set-enviroment:
    name: Set enviroment
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.enviroment }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set enviroment
        id: set-env
        uses: ./.github/actions/set-environment
