name: Create Markdown File

on:
  release:
    types: [published]

jobs:
  create-md-file:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create markdown file
        run: |
          TAG_VERSION=${{ github.event.release.tag_name }}
          FILE_NAME="public/release-notes/${TAG_VERSION##*/}.md"
          echo "# Release Information" > $FILE_NAME
          echo "## Name: ${{ github.event.release.name }}" >> $FILE_NAME
          echo "## Description: ${{ github.event.release.body }}" >> $FILE_NAME

      - name: Configure git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Commit markdown file
        run: |
          TAG_VERSION=${{ github.ref }}
          FILE_NAME="public/release-notes/${TAG_VERSION##*/}.md"
          git pull --rebase
          git add $FILE_NAME
          git commit -m "Generate Release markdown for $TAG_VERSION"
          git push origin HEAD:main
